version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    restart: always
    expose:
      - "7077"
    ports:
      - "8181:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./spark:/spark
  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    restart: always
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8083:8083"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./spark:/zeppelin/spark
      - ./zeppelin/notebook:/zeppelin/notebook
      - ./zeppelin/logs:/zeppelin/logs
    environment:
      - "MASTER=spark://spark-master:7077"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/zeppelin/spark"